### ISSUE TITLE
Nuxt3 bug: require is not defined in ES module scope, you can use import instead

### ISSUE THREAD

**Issue by larbish** [larbish/supabase-module#14]
### Version
On the dev branch of this repo, latest version of nuxt

### Steps to reproduce
1) Clone the `supabase-module` and goes to the `dev` branch
2) `yarn`, `yarn build` and `yarn link`
3) Go on the repo using the module, you can use [pushupers](https://github.com/nuxtlabs/pushupers/tree/dev)
4) `yarn` then `yarn link @larbish/supabase` 
5) `yarn dev`
6) Constat the error: `require is not defined in ES module scope, you can use import instead`

### What is Expected?
No error, website loading normally. 

### What is actually happening? 
The require statement is coming from `cross-fetch ` , dependency of `supabase/supabase-js`, itself used by the module. 
Nuxt does not transpile it. 
I already tried:
`nuxt.options.build.transpile.push()`  and  `nuxt.options.vite = { optimizeDeps: { include: [] } } ` for both `cross-fetch` and `supabase/supabase-js` but without success.

**Comment by pi0** [comment]
Hi. The issue is likely caused because using the linked package which is outside of `node_modules` and not being transpiled for CommonJS require.  Also made a test publish on `@pi0/supabase` and works well for pushupers repo both dev and prod.

Will improve Nuxt to replace `cross-fetch` with native (https://github.com/nuxt/framework/issues/3421) but probably not an issue to solve here.

**Comment by larbish** [comment]
Thanks @pi0 for the feedback. Even when using a published version, I still have an error on runtime: `Uncaught SyntaxError: The requested module '/_nuxt/node_modules/cross-fetch/dist/browser-ponyfill.js?v=d0e09cad' does not provide an export named 'default' `.

**Comment by larbish** [comment]
After a new attempt, adding `cross-fetch` to the `optimiseDeps` of `vite` fixes the problem: https://github.com/larbish/supabase-module/commit/66d0aa1e515dff3b43ed9903c48a033197749f96#diff-030fc083b2cbf5cf008cfc0c49bb4f1b8d97ac07f93a291d068d81b4d1416f70R106

**Comment by zzxxiinn** [comment]
any progress?

**Comment by larbish** [comment]
@zzxxiinn Yes it is fixed. However, this module is no more on my personal account, it has just been moved to the `nuxt-community` organization. You can now install it with `yarn add --dev @nuxtjs/supabase` and no more with `@larbish/supabase`. Documentation is ready: https://supabase.nuxtjs.org/setup

**Comment by zzxxiinn** [comment]
@larbish Thank you for your reply!
