### ISSUE TITLE
Moving to Nuxt community

### ISSUE THREAD

**Issue by pi0** [larbish/supabase-module#8]
In order to pick this module and unify it for nuxt-community-recommended solution, I suggest at least two changes:

- For auth support, using only nitro API for session handling, is probably not the best practice. A server-only vue composable should be able to handle the same logic while also allowing client-side login flows as well when client-only rendering is used.
- In order to merge and take over [nuxt-supabase](https://github.com/supabase-community/nuxt-supabase) which is currently listed as supabase solution in modules website, we need to also consider support client possibilities for query with either [vue-supabase](https://github.com/supabase-community/vue-supabase) or [supabase-js](https://github.com/supabase/supabase-js)

**Comment by larbish** [comment]
Hello @pi0, the module now handles auth for client side only application. Concerning the point about querying with either [vue-supabase](https://github.com/supabase-community/vue-supabase) or [supabase-js](https://github.com/supabase/supabase-js), vue-supabase itself use supabase-js and thanks to the `useSupabaseClient` composable, all client possibilites handled by vue-supabase are availlable with this module: see the [usage](https://github.com/larbish/supabase-module/blob/main/docs/pages/4.usage.md#usesupabaseclient) section of the doc. I'll let you discuss with @Atinux during the framework meeting about the future of this module.

**Comment by larbish** [comment]
Thanks both @Atinux @pi0 for the found and illustration. Here is the [fix](https://github.com/larbish/supabase-module/blob/main/src/runtime/composables/useSupabaseClient.ts#L12). 

Concerning the auth, supabase auth is mandatory the way it is implemented. Don't hesitate to explain if you have other ideas in mind.
